name: Deploy Main
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - package.json

jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install modules
        run: npm i --ignore-scripts --legacy-peer-deps
      - name: Build Blocks
        run: npm run build:blocks
      - name: Upload to Web3.Storage
        run: node ./scripts/upload.mjs ./dist/assets/blocks
        env:
          WEB3STORAGE_TOKEN: ${{ secrets.WEB3STORAGE_TOKEN }}
